[template.environment]
  REACT_APP_TEXT_RAZOR_API_KEY = "REACT_APP_TEXT_RAZOR_API_KEY"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/*"
  to = "https://api.textrazor.com"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}